[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

; --- ESP32-C3 Super Mini USB settings ---
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

; --- Libraries used by the sketch ---
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit GC9A01A
    bitbank2/AnimatedGIF
